### ISSUE TITLE
Unable to start bot

### ISSUE THREAD

**Issue by TeamColaDev** [aoijs/aoi.js#269] opened 2021-08-23 19:29 UTC
## Type
- [ ] Functions: \<Function Name>
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

Code used:
```
Your Code Here
```

More:
- Aoi.js version:
- Node.js version:
- Operating system:

Screenshots (If any): Image or Link

**Comment by Leref** [comment] 2021-08-24 14:08
Duplicate of #270

**Closed** 2021-08-24 14:08 UTC
