### ISSUE TITLE
Bug: Timeouts are bugged

### ISSUE THREAD

**Issue by tavaresmp4** [aoijs/aoi.js#616] opened 2024-06-11 21:46 UTC
### Bug Type

Function

### Bugged Function

```js
... , {
    type: 'interaction',
    prototype: 'button',
    code: `
$interactionReply[${Emojis.Raio}｜Caçada **rápida** iniciada! Em \`30 minutos\` você pode usar esse comando de novo e resgatar sua recompensa.;;true]

$editMessage[$interactionData[message.id];{newEmbed:
    {title:$ifAwaited[$getGlobalUserVar[userHuntType]==1;${Emojis.Raio};${Emojis.Barco}]｜Caçada em andamento...}
    {description:> Você tem uma caçada **$ifAwaited[$getGlobalUserVar[userHuntType]==1;rápida;longa]** em andamento, volte <t:$truncate[$divide[$getGlobalUserVar[cooldownHunt;$authorID];1000]]:R>!}
    {color:${Cores.Amarelo}}
}{actionRow:
    {button:Ativar lembrete:secondary:huntReminder_$advancedTextSplit[$interactionData[customId];_;2]_$sum[$datestamp;600000]:false:1249838446688731188}
}]

$setTimeout[fastHuntTimeout;1800000;{ "authorID": "$interactionData[author.id]" }]

$setGlobalUserVar[userHuntType;1;$interactionData[author.id]]
$setGlobalUserVar[cooldownHunt;$sum[$datestamp;1800000];$interactionData[author.id]]

$onlyIf[$advancedTextSplit[$interactionData[customId];_;2]==$interactionData[author.id];${Emojis.KiaraRaiva}｜Meow! Você não pode usar esse botão! Somente <@$advancedTextSplit[$interactionData[customId];_;2]> pode usar isso!{interaction}{ephemeral}]
$onlyIf[$advancedTextSplit[$interactionData[customId];_;3]>=$datestamp;${Emojis.KiaraSeiLa}｜Parece que os dados dessa interação não existem mais. Eu não comi eles! Eu acho...{interaction}{ephemeral}]
$onlyIf[$advancedTextSplit[$interactionData[customId];_;1]==fastHunt;]
    `
}, {
    name: 'fastHuntTimeout',
    type: 'timeout',
    code: `
$setGlobalUserVar[hasHuntReward;true;$timeoutData[authorID]]
    `
} ...
```

### Version of aoi.js

v6.8.0

### Version of Node.js

v20.10.0 (LTS)

### Excepted Output

# VERSION:
- I'm using version v6.8.0 of aoi.js and previously I used the github version and the same thing happened.

# What happend:
- The timeout didn't run after I restarted, although the wiki says it should work and was fixed in version 6.8.0, but it's not working for me. The only thing I use differently in my bot is that the database I use is mongoDB, using aoi.mongo an unofficial extension.

### Relevant log output

Any error on console or chat

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by USERSATOSHI** [comment] 2024-06-18 18:46
so it didn't set value to true 30 mins??

**Comment by tavaresmp4** [comment] 2024-06-19 23:36
> so it didn't set value to true 30 mins??

yeah, if i restart the bot the timeout dont execute, but if i dont restart it work, so timeouts are broken again...

**Comment by atlasfyber** [comment] 2024-06-22 21:04
I can confirm, if you restart the bot, then previous timeouts never execute, although you can find the on the database as usual. I also use Mongo (once again)

**Comment by Modyes** [comment] 2024-06-22 23:50
Yeah, also aoi.db is too slow that even interactions now fail to work cause it takes too much time to get var values

**Comment by Modyes** [comment] 2024-06-23 00:27
And my database got corrupted all of a sudden..
![image](https://github.com/aoijs/aoi.js/assets/84382848/54307d6c-61e8-4d3e-9ad4-c6b17de7dcd4)
![image](https://github.com/aoijs/aoi.js/assets/84382848/fa56ba1d-080d-4ebc-bacd-70e98ab8ffb8)

**Comment by atlasfyber** [comment] 2024-06-23 03:37
That's how json works, try switch to mongo, also I think it's off topic for this issue

**Comment by LaurensTheDev** [comment] 2024-06-23 07:11
> yeah, if i restart the bot the timeout dont execute, but if i dont restart it work, so timeouts are broken again...

i can confirm as well

**Comment by Faf4a** [comment] 2024-07-05 17:11
Does this still happen in the dev version?

**Comment by atlasfyber** [comment] 2024-07-05 17:16
> Does this still happen in the dev version?

It's not working on stable version 6.8, is it fixed on dev? Should I try it on dev?

**Comment by Faf4a** [comment] 2024-07-05 19:35
i can't reproduce this at all, so no clue

**Comment by atlasfyber** [comment] 2024-07-05 20:59
> i can't reproduce this at all, so no clue

Github version or npm (stable)?

**Comment by Faf4a** [comment] 2024-07-09 19:16
stable, 6.8.5, works fine for me

**Comment by Leref** [comment] 2024-07-30 15:59
Seems solved.

**Closed as completed** 2024-09-03 23:43 UTC
Labels: type: bug, state: needs reproduction, @aoijs/aoi.db

**Comment by tavaresmp4** [comment] 2024-11-12 17:42
yaaay, after a couple of months it works again for me LOL
